bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "search" => "searches#search"

  resources :users do
    resource :relationships
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books do
    resource :favorites
    resources :book_comments
  end

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search, model, how)
    if how == "partical"
  	  Book.where("title LIKE ?", "%#{search}%")
    elsif how == "forward"
  	  Book.where("title LIKE ?", "#{search}%")
    elsif how == "backward"
  	  Book.where("title LIKE ?", "%#{search}")
    elsif how == "match"
  	  Book.where("title LIKE ?", "#{search}")
    end
  end


end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def User.search(search, model, how)
    if model == "user"
      if how == "partical"
        User.where("name LIKE ?", "%#{search}%")
      elsif how == "forward"
        User.where("name LIKE ?", "#{search}%")
      elsif how == "backward"
        User.where("name LIKE?", "%#{search}")
      elsif how == "match"
        User.where("name LIKE?", "#{search}")
      end
    end
  end

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :authenticate_user!,only: [:new, :create, :index, :edit, :show, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
	  user_path(resource)
  end

  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @user = current_user
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
  	redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)

    #favorite = Favorite.new
    #favorite.user_id = current_user.id
    #favorite.book_id = @book.id

    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def top
    end

    def about
    end

end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
  	@model = params[:search][:model]
    @how = params[:search][:how]
    @value = params[:search][:value]

    if @model == "user"
      @users = User.search(@value, @model, @how)
    else
      @books = Book.search(@value, @model, @how)
    end
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_edit_check, only: [:edit]
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice]="You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def user_edit_check
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/_list.html.erb
<div class="col-md-3">

    <!--ユーザー-->
    <h2>User info</h2>

    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>

    <table class="table">
      <tbody>
        <tr></tr>

        <tr>
          <th>name</th>
          <th></th>
          <th><%= user.name %></th>
        </tr>

        <tr>
          <th>introduction</th>
          <th></th>
          <th><%= user.introduction %></th>
        </tr>

        <tr>
          <th>follows</th>
          <th></th>
          <th><%= link_to user.followings.count, user_followings_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th></th>
          <th><%= link_to user.followers.count, user_followers_path(user) %></th>
        </tr>

     </tbody>
    </table>

    <!--編集ボタン-->
    <% unless current_user != user %>
    <div class="row">
      <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
    <% end %>

    <!--フォローボタン-->
    <div class="row">
      <%= render "relationships/follow_button", user: user %>
    </div>


    <!--投稿フォーム-->
    <h2 class="mt-3">New book</h2>

    <%= form_with model:book, local:true do |f| %>
      <div class="form-group">
        <p>Title</p>
         <p><%= f.text_field :title, class:"form-control" %></p>
      </div>

      <div class="form-group">
         <p>Opinion</p>
         <p><%= f.text_area :body, class:"form-control"  %></p>
      </div>

      <div>
         <p><%= f.submit "Create Book", class:"btn btn-success" %></p>
      </div>
    <% end %>

  </div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

 <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class:"navbar-brand" %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                  <li><%= link_to user_path(current_user), class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                    <% end %>
                  </li>

                  <li><%= link_to users_path, class:"nav-link text-light" do %>
                    <i class="fas fa-users"></i> Users
                    <% end %>
                  </li>

                  <li><%= link_to books_path, class:"nav-link text-light" do %>
                    <i class="fas fa-book-open"></i> Books
                    <% end %>
                  </li>

                  <li><%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> logout
                    <% end %>
                  </li>

                <% else %>
                  <li><%= link_to root_path, class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                    <% end %>
                  </li>

                  <li><%= link_to home_about_path, class:"nav-link text-light" do %>
                    <i class="fas fa-link"></i> About
                    <% end %>
                  </li>

                  <li><%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i> sign up
                    <% end %>
                  </li>

                  <li><%= link_to new_user_session_path, class:"nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> login
                    <% end %>
                  </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
    <p id="notice">
        <%= flash[:notice] %>
    </p>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>

  </body>
</html>