bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "search" => "searches#search"

  resources :users do
    resource :relationships
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books do
    resource :favorites
    resources :book_comments
  end

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search, model, how)
    if how == "partical"
  	  Book.where("title LIKE ?", "%#{search}%")
    elsif how == "forward"
  	  Book.where("title LIKE ?", "#{search}%")
    elsif how == "backward"
  	  Book.where("title LIKE ?", "%#{search}")
    elsif how == "match"
  	  Book.where("title LIKE ?", "#{search}")
    end
  end


end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def User.search(search, model, how)
    if model == "user"
      if how == "partical"
        User.where("name LIKE ?", "%#{search}%")
      elsif how == "forward"
        User.where("name LIKE ?", "#{search}%")
      elsif how == "backward"
        User.where("name LIKE?", "%#{search}")
      elsif how == "match"
        User.where("name LIKE?", "#{search}")
      end
    end
  end

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :authenticate_user!,only: [:new, :create, :index, :edit, :show, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
	  user_path(resource)
  end

  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end

end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id

    if @book_comment.save
      flash[:notice]="Book was successfully created"
    else
      render "books/show"
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
      flash[:notice]="Comment was successfully destroyed."
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @user = current_user
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
  	redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)

    #favorite = Favorite.new
    #favorite.user_id = current_user.id
    #favorite.book_id = @book.id

    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def top
    end

    def about
    end

end

bookers2/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_back fallback_location: root_url
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back fallback_location: root_url
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
  	@model = params[:search][:model]
    @how = params[:search][:how]
    @value = params[:search][:value]

    if @model == "user"
      @users = User.search(@value, @model, @how)
    else
      @books = Book.search(@value, @model, @how)
    end
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_edit_check, only: [:edit]
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice]="You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def user_edit_check
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/book_comments/_comment_form.html.erb
<%= form_with(model:[book, book_comment]) do |f| %>

  <p><%= f.text_area :comment, rows:'5', class: "form-control" %></p>
  <p><%= f.submit "送信" %></p>

<% end %>

bookers2/app/views/book_comments/_comment_list.html.erb
<h3>Comments</h3>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Comment</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <% book.book_comments.each do |book_comment| %>
    <tr>
      <td><%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>

      <td>
      <%= link_to book_comment.user do %>
      <%= book_comment.user.name %>
      <% end %>
      </td>

      <td><%= book_comment.comment %></td>

      <% if book_comment.user_id == current_user.id %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-sm btn-danger" %></td>
      <% else %>
      <td></td>
      <% end %>

      <td class="small"><%= book_comment.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
    </tr>
    <% end %>

  </tbody>
</table>

bookers2/app/views/book_comments/create.js.erb
$("#comment_list").html("<%= j(render "book_comments/comment_list", book: @book ) %>")
$("textarea").val('')

bookers2/app/views/book_comments/destroy.js.erb
$("#comment_list").html("<%= j(render "book_comments/comment_list", book: @book ) %>")
$("textarea").val('')

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>

      <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <p>Title</p>
        <p><%= f.text_field :title, autofocus: true, class:"form-control" %></p>
      </div>

      <div class="form-group">
        <p>Opinion</p>
        <p><%= f.text_area :body, autofocus: true, class:"form-control" %></p>
      </div>

      <div class="form-group">
        <p><%= f.submit "Update Book", class:"btn btn-success" %></p>
      </div>
      <% end %>

      <p><%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %></p>

    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<!--検索窓-->
<div class="container">
  <div class="text-center">
    <%= render "searches/search_form" %>
  </div>
</div>

<div class="container">

  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

    <% end %>
  </div>

  <div class="row">

    <%= render 'layouts/list', book: Book.new, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                 <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>

              <td id="favorite_<%= book.id %>"><%= render "favorites/favorite", book: book %></td>

              <td>コメント数: <%= book.book_comments.count %></td>

              <td class="small"><%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></td>

             </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<!--検索窓-->
<div class="container">
  <div class="text-center">
    <%= render "searches/search_form" %>
  </div>
</div>

<div class="container">
  <div class="row">

    <%= render 'layouts/list', book: Book.new, user: @book.user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>

            <td>
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>

            <td><%= @book.body %></td>

            <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger" %></td>
            <% end %>

            <td id="favorite_<%= @book.id %>"><%= render "favorites/favorite", book: @book %></td>

            <td>コメント数: <%= @book.book_comments.count %></td>

          </tr>
        </tbody>
      </table>

      <!--コメント機能-->
      <div id="comment_list">
        <%= render "book_comments/comment_list", book: @book %>
      </div>

      <%= render "book_comments/comment_form", book: @book, book_comment: @book_comment %>

    </div>

  </div>
</div>

bookers2/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

  <div class="LikesIcon">
    <%= link_to book_favorites_path(book), class:"like", method: :delete, remote: true do %>
      <i class="fas fa-heart"></i>
    <% end %>
    <%= book.favorites.count %>

  <% else %>

    <%= link_to book_favorites_path(book), class:"like", method: :post, remote: true do%>
      <i class="far fa-heart"></i>
    <% end %>
    <%= book.favorites.count %>
  </div>

<% end %>

bookers2/app/views/favorites/create.js.erb
$("#favorite_<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book ) %>");

bookers2/app/views/favorites/destroy.js.erb
$("#favorite_<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book ) %>");

bookers2/app/views/homes/about.html.erb
<h1>Welcom to
  <b><i class="fas fa-book"></i>Bookers!!</b>
</h1>

bookers2/app/views/homes/top.html.erb
<% if flash[:notice] %>
    <p id="notice">
        <%= flash[:notice] %>
    </p>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>

      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>

        <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
        </div>
      </div>

    </div>
  </div>
</div>

bookers2/app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn btn-sm btn-secondary" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-success" %>
  <% end %>
<% end %>

bookers2/app/views/relationships/_follow_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Follows</th>
      <th>Follows</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.followings.count %></td>
      <td>フォロワー数:<%= user.followers.count %></td>
      <td></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

bookers2/app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">
    <h2>Follower Users</h2>

    <% if @users.present? %>
      <%= render "relationships/follow_list", user: @user, users:@users %>
    <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Follows</th>
          <th>Follows</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>ユーザーはいません</td>
        </tr>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

bookers2/app/views/relationships/followings.html.erb
<div class="container">
  <div class="row">
    <h2>Follow Users</h2>

    <% if @users.present? %>
      <%= render "relationships/follow_list", user: @user, users:@users %>
    <% else %>
     <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Follows</th>
          <th>Follows</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>ユーザーはいません</td>
        </tr>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

bookers2/app/views/searches/_search_form.html.erb
<% if user_signed_in? %>

  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field "search[value]" %>
    <%= f.select "search[model]", options_for_select([["User","user"], ["Book","book"]]) %>
    <%= f.select "search[how]", options_for_select([["完全一致","match"], ["部分一致","partical"], ["前方一致","forward"], ["後方一致","backward"]]) %>
    <%= f.submit "検索" %>
   <% end %>

<% end %>

bookers2/app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <table class="table">

<!--ユーザー検索-->
<% if @model == "user" %>
  <h2>Users search for " <%= @value %> "</h2>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Follows</th>
      <th>Follows</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% if @users.present? %>
    <tbody>
      <% @users.each do |user| %>
      <tr>
       <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
       <td><%= user.name %></td>
       <td>フォロー数:<%= user.followings.count %></td>
       <td>フォロワー数:<%= user.followers.count %></td>
       <td></td>
       <td><%= link_to "Show", "/users/#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <tr>
        <td>該当のユーザーはいません</td>
      </tr>
    </tbody>
  <% end %>

<!--ブック検索-->
<% elsif @model == "book" %>
  <h2>Books search for " <%= @value %> "</h2>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>コメント数</th>
      <th></th>
    </tr>
  </thead>

  <% if @books.present? %>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>
        <td><%= book.user.name %></td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><%= book.book_comments.count %></td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <tr>
        <td>該当の本はありません</td>
      </tr>
    </tbody>
  <% end %>
<% end %>

    </table>
  </div>
</div>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      
      <div id="error_explanation">
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_with model: @user, local: true do |f| %>

      <div class="form-group">
        <p>Name</p>
        <p><%= f.text_field :name, autofocus: true, class:"form-control" %></p>
      </div>

      <div class="form-group">
        <p>Image</p>
        <p><%= f.attachment_field :profile_image %></p>
      </div>


      <div class="form-group">
        <p>Introduction</p>
        <p><%= f.text_area :introduction, autofocus: true, class:"form-control" %></p>
      </div>

      <div class="form-group">
        </p><%= f.submit "Update User", class:"btn btn-secondary" %></p>
      </div>

      <% end %>

    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<!--検索窓-->
<div class="container">
  <div class="text-center">
    <%= render "searches/search_form" %>
  </div>
</div>

<div class="container">
  <div class="row">

    <%= render 'layouts/list', book: Book.new, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
	  	  	    <td><%= user.name %></td>
	  	  	    <td>フォロー数:<%= user.followings.count %></td>
	  	  	    <td>フォロワー数:<%= user.followers.count %></td>
	  	  	    <td><%= render "relationships/follow_button", user: user %></td>
	  	  	    <td><%= link_to "Show", "/users/#{user.id}" %></td>
            </tr>
            <% end %>
          </tbody>
        </thead>
      </table>

    </div>

  </div>
</div>

bookers2/app/views/users/show.html.erb
<!--検索窓-->
<div class="container">
  <div class="text-center">
    <%= render "searches/search_form" %>
  </div>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'layouts/list', book: Book.new, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
            </td>

            <td><%= link_to book.title, book_path(book.id) %></td>

            <td><%= book.body %></td>

            <td id="favorite_<%= book.id %>"><%= render "favorites/favorite", book: book %></td>

            <td>コメント数: <%= book.book_comments.count %></td>

            <td class="small"><%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></td>

          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>